spring:
  profiles:
    active: prod

server:
  servlet:
    context-path: /api

jwt:
  expirationAt: 3600000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

sse:
  timeout: 3600000